name=UartLcd
version=1.0.0
author=karorero vainqueur
maintainer=karorerovainqueur@gmail.com>
sentence=A simple library to control 20x4 UART Serial LCDs.
paragraph=This library handles hex commands for clearing the screen and setting cursor positions on 20x4 UART displays using SoftwareSerial.
category=Display
url=https://github.com/vainqueurkaro/UartLcd
architectures=VENDOR HUB
includes=UartLcd.h